/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SsoController_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SsoController_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SsoController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health check */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and optionally filter places */
        get: operations["PlacesController_findAll"];
        put?: never;
        /** Create a place (editor or admin) */
        post: operations["PlacesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search places by room, keyword, or lecturer */
        get: operations["PlacesController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/admin-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active and inactive places for administration */
        get: operations["PlacesController_adminList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return dashboard counts for editors and admins */
        get: operations["PlacesController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/layout-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the editable map corridor layout */
        get: operations["PlacesController_mapLayout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/core-rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlacesController_coreRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a place by UUID */
        get: operations["PlacesController_findOne"];
        put?: never;
        post?: never;
        /** Delete a place (admin only) */
        delete: operations["PlacesController_remove"];
        options?: never;
        head?: never;
        /** Update a place (editor or admin) */
        patch: operations["PlacesController_update"];
        trace?: never;
    };
    "/api/v1/places/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update positions and sizes for multiple places */
        patch: operations["PlacesController_updateLayout"];
        trace?: never;
    };
    "/api/v1/lecturers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List lecturers with their assigned offices */
        get: operations["LecturersController_findAll"];
        put?: never;
        post: operations["LecturersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lecturers/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search lecturers by partial name or email */
        get: operations["LecturersController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lecturers/core-people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LecturersController_corePeople"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lecturers/directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the active department personnel directory from Core Hub */
        get: operations["LecturersController_directory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lecturers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["LecturersController_remove"];
        options?: never;
        head?: never;
        patch: operations["LecturersController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LecturerSummaryDto: {
            id: string;
            personCode: string;
            nameTh: string;
            nameEn: string | null;
            email: string | null;
            /** @enum {string} */
            personnelType: "TEACHER" | "STAFF";
        };
        PlaceResponseDto: {
            id: string;
            roomCode: string | null;
            nameTh: string;
            nameEn: string | null;
            description: string | null;
            /** @enum {string} */
            category: "CLASSROOM" | "COMPUTER_LAB" | "LECTURER_OFFICE" | "DEPARTMENT_OFFICE" | "MEETING_ROOM" | "RESTROOM" | "ENTRANCE" | "FACILITY" | "STUDENT_CLUB" | "STORAGE" | "OTHER";
            positionX: number;
            positionY: number;
            width: number | null;
            height: number | null;
            isActive: boolean;
            lecturers: components["schemas"]["LecturerSummaryDto"][];
            keywords: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginationMetaDto: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
        ApiEnvelopeDto: {
            /** @enum {boolean} */
            success: true;
            data: Record<string, never>;
            meta?: components["schemas"]["PaginationMetaDto"];
        };
        ApiErrorDto: {
            code: string;
            message: string;
            details?: Record<string, never>;
        };
        ApiErrorEnvelopeDto: {
            /** @enum {boolean} */
            success: false;
            error: components["schemas"]["ApiErrorDto"];
        };
        Object: Record<string, never>;
        DashboardStatsDto: {
            totalPlaces: number;
            totalClassrooms: number;
            totalLabs: number;
            totalLecturerOffices: number;
            totalActive: number;
        };
        MapPointDto: {
            x: number;
            y: number;
        };
        MapLayoutDto: {
            corridorPoints: components["schemas"]["MapPointDto"][];
            corridorWidth: number;
        };
        CoreRoomDto: {
            code: string;
            nameTh: string;
            isActive: boolean;
            updatedAt: string;
        };
        CreatePlaceDto: {
            /** @example LAB-03 */
            roomCode?: string;
            /** @description ชื่อจุดบนแผนที่ที่ไม่ใช่ห้องของ Core Hub */
            nameTh?: string;
            description?: string;
            /** @enum {string} */
            category: "CLASSROOM" | "COMPUTER_LAB" | "LECTURER_OFFICE" | "DEPARTMENT_OFFICE" | "MEETING_ROOM" | "RESTROOM" | "ENTRANCE" | "FACILITY" | "STUDENT_CLUB" | "STORAGE" | "OTHER";
            positionX: number;
            positionY: number;
            /** @default 12 */
            width: number;
            /** @default 8 */
            height: number;
            /** @default true */
            isActive: boolean;
            keywords?: string[];
        };
        BulkLayoutDto: {
            places: components["schemas"]["PlaceResponseDto"][];
            mapLayout: components["schemas"]["MapLayoutDto"];
        };
        PlaceLayoutItemDto: {
            /** Format: uuid */
            id: string;
            positionX: number;
            positionY: number;
            width: number;
            height: number;
        };
        CorridorPointDto: {
            x: number;
            y: number;
        };
        UpdateCorridorDto: {
            corridorPoints: components["schemas"]["CorridorPointDto"][];
            corridorWidth: number;
        };
        UpdatePlacesLayoutDto: {
            items?: components["schemas"]["PlaceLayoutItemDto"][];
            corridor?: components["schemas"]["UpdateCorridorDto"];
        };
        UpdatePlaceDto: {
            /** @example LAB-03 */
            roomCode?: string;
            /** @description ชื่อจุดบนแผนที่ที่ไม่ใช่ห้องของ Core Hub */
            nameTh?: string;
            description?: string;
            /** @enum {string} */
            category?: "CLASSROOM" | "COMPUTER_LAB" | "LECTURER_OFFICE" | "DEPARTMENT_OFFICE" | "MEETING_ROOM" | "RESTROOM" | "ENTRANCE" | "FACILITY" | "STUDENT_CLUB" | "STORAGE" | "OTHER";
            positionX?: number;
            positionY?: number;
            /** @default 12 */
            width: number;
            /** @default 8 */
            height: number;
            /** @default true */
            isActive: boolean;
            keywords?: string[];
        };
        DeletedRecordDto: {
            id: string;
            /** @enum {boolean} */
            deleted: true;
        };
        AssignmentPlaceDto: {
            id: string;
            roomCode: string | null;
            nameTh: string;
            nameEn: string | null;
            /** @enum {string} */
            category: "CLASSROOM" | "COMPUTER_LAB" | "LECTURER_OFFICE" | "DEPARTMENT_OFFICE" | "MEETING_ROOM" | "RESTROOM" | "ENTRANCE" | "FACILITY" | "STUDENT_CLUB" | "STORAGE" | "OTHER";
            positionX: number;
            positionY: number;
            isActive: boolean;
        };
        LecturerResponseDto: {
            id: string;
            personCode: string;
            nameTh: string;
            nameEn: string | null;
            email: string | null;
            /** @enum {string} */
            personnelType: "TEACHER" | "STAFF";
            sourceId: number | null;
            title: string | null;
            positionAcademic: string | null;
            positionManager: string | null;
            imageProfile: string | null;
            phone: string | null;
            education: string | null;
            academicType: string | null;
            placeId: string | null;
            place: components["schemas"]["AssignmentPlaceDto"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CorePersonOptionDto: {
            personCode: string;
            nameTh: string;
            personnelType: string;
        };
        PersonnelDirectoryDto: {
            personCode: string;
            nameTh: string;
            nameEn: string | null;
            email: string | null;
            /** @enum {string} */
            personnelType: "TEACHER" | "STAFF";
            positionAcademic: string | null;
            positionManager: string | null;
        };
        CreateLecturerDto: {
            /** @description personCode จาก Core Hub */
            personCode: string;
            /** Format: uuid */
            placeId?: string | null;
        };
        UpdateLecturerDto: {
            /** @description personCode จาก Core Hub */
            personCode?: string;
            /** Format: uuid */
            placeId?: string | null;
        };
        SessionDto: {
            /** Format: date-time */
            expiresAt: string | null;
        };
        CurrentUserDto: {
            id: string;
            email: string;
            /** @enum {string} */
            coreRole: "student" | "alumni" | "staff" | "lecturer" | "guest" | "admin";
            /** @enum {string} */
            subsystemRole: "STUDENT" | "ALUMNI" | "STAFF" | "ADMIN";
            session: components["schemas"]["SessionDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verified Core Hub identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["CurrentUserDto"];
                    };
                };
            };
        };
    };
    SsoController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Core Hub SSO redirect */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SsoController_callback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Core Hub SSO redirect */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SsoController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Core Hub SSO redirect */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlacesController_findAll: {
        parameters: {
            query?: {
                page?: components["schemas"]["Object"];
                limit?: components["schemas"]["Object"];
                /** @description Partial match across names, room code, lecturers, and keywords */
                q?: string;
                category?: "CLASSROOM" | "COMPUTER_LAB" | "LECTURER_OFFICE" | "DEPARTMENT_OFFICE" | "MEETING_ROOM" | "RESTROOM" | "ENTRANCE" | "FACILITY" | "STUDENT_CLUB" | "STORAGE" | "OTHER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PlaceResponseDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    PlacesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlaceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PlaceResponseDto"];
                    };
                };
            };
        };
    };
    PlacesController_search: {
        parameters: {
            query: {
                page?: components["schemas"]["Object"];
                limit?: components["schemas"]["Object"];
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PlaceResponseDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    PlacesController_adminList: {
        parameters: {
            query?: {
                page?: components["schemas"]["Object"];
                limit?: components["schemas"]["Object"];
                /** @description Partial match across names, room code, lecturers, and keywords */
                q?: string;
                category?: "CLASSROOM" | "COMPUTER_LAB" | "LECTURER_OFFICE" | "DEPARTMENT_OFFICE" | "MEETING_ROOM" | "RESTROOM" | "ENTRANCE" | "FACILITY" | "STUDENT_CLUB" | "STORAGE" | "OTHER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PlaceResponseDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    PlacesController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DashboardStatsDto"];
                    };
                };
            };
        };
    };
    PlacesController_mapLayout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["MapLayoutDto"];
                    };
                };
            };
        };
    };
    PlacesController_coreRooms: {
        parameters: {
            query?: {
                page?: components["schemas"]["Object"];
                limit?: components["schemas"]["Object"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["CoreRoomDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    PlacesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PlaceResponseDto"];
                    };
                };
            };
        };
    };
    PlacesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedRecordDto"];
                    };
                };
            };
        };
    };
    PlacesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlaceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PlaceResponseDto"];
                    };
                };
            };
        };
    };
    PlacesController_updateLayout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlacesLayoutDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["BulkLayoutDto"];
                    };
                };
            };
        };
    };
    LecturersController_findAll: {
        parameters: {
            query?: {
                page?: components["schemas"]["Object"];
                limit?: components["schemas"]["Object"];
                q?: string;
                personnelType?: "TEACHER" | "STAFF";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LecturerResponseDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    LecturersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLecturerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LecturerResponseDto"];
                    };
                };
            };
        };
    };
    LecturersController_search: {
        parameters: {
            query?: {
                page?: components["schemas"]["Object"];
                limit?: components["schemas"]["Object"];
                q?: string;
                personnelType?: "TEACHER" | "STAFF";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LecturerResponseDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    LecturersController_corePeople: {
        parameters: {
            query?: {
                page?: components["schemas"]["Object"];
                limit?: components["schemas"]["Object"];
                q?: string;
                personnelType?: "TEACHER" | "STAFF";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["CorePersonOptionDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    LecturersController_directory: {
        parameters: {
            query?: {
                page?: components["schemas"]["Object"];
                limit?: components["schemas"]["Object"];
                q?: string;
                personnelType?: "TEACHER" | "STAFF";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PersonnelDirectoryDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    LecturersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedRecordDto"];
                    };
                };
            };
        };
    };
    LecturersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLecturerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LecturerResponseDto"];
                    };
                };
            };
        };
    };
}
