-- AlterEnum
ALTER TYPE "PlaceCategory" ADD VALUE IF NOT EXISTS 'FACILITY';
ALTER TYPE "PlaceCategory" ADD VALUE IF NOT EXISTS 'STUDENT_CLUB';
ALTER TYPE "PlaceCategory" ADD VALUE IF NOT EXISTS 'STORAGE';
